<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors>nullable</WarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>false</ContinuousIntegrationBuild>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591;NU1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>CacheHub Contributors</Authors>
    <Product>CacheHub</Product>
    <Copyright>Copyright (c) 2026 CacheHub Contributors</Copyright>
    <Version>0.2.0-prealpha</Version>
  </PropertyGroup>

</Project>
