<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CacheHub.Core\CacheHub.Core.csproj" />
    <ProjectReference Include="..\CacheHub.Storage\CacheHub.Storage.csproj" />
    <ProjectReference Include="..\CacheHub.Context\CacheHub.Context.csproj" />
    <ProjectReference Include="..\CacheHub.Indexing\CacheHub.Indexing.csproj" />
    <ProjectReference Include="..\CacheHub.Gateway\CacheHub.Gateway.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>cachehub</AssemblyName>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>false</PublishTrimmed>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

</Project>
