<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CacheHub.Core\CacheHub.Core.csproj" />
    <ProjectReference Include="..\CacheHub.Storage\CacheHub.Storage.csproj" />
    <ProjectReference Include="..\CacheHub.Indexing\CacheHub.Indexing.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
